CREATE SCHEMA bank;

DROP TABLE user IF EXISTS;
DROP TABLE check IF EXISTS;
DROP TABLE transactions IF EXISTS;


CREATE TABLE transaction
(
	id_transaction INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	checknumbersender INT NOT NULL,
	checknumberrecipient INT NOT NULL,
	summa INT,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE check
(
	id_check INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
	checknumber INT NOT NULL,
	summa INT NOT NULL,
	id_transaction INT,
--	CONSTRAINT fk_check_transaction FOREIGN KEY (id_transaction) REFERENCES transactions (id)
);

CREATE TABLE user (
  id_user INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
  login VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  -- enabled boolean NOT NULL,
  firstname VARCHAR(50) NOT NULL,
  secondname VARCHAR(50) NOT NULL,
  id_check INT,
--  CONSTRAINT fk_user_check FOREIGN KEY (id_check) REFERENCES check (id)
);